config/routes.rb
Milosz::Application.routes.draw do

  resources :quotes

  resources :poems

        get '/about', to: 'about#index'
        get '/biography', to: 'biography#index'
        get '/poems', to: 'poems#index'
        get '/quotes', to: 'quotes#index'
        get '/contact', to: 'contact#index'
        get '/links', to: 'links#index'
        root 'home#index'
        

end

app/models/keyword.rb
class Keyword < ActiveRecord::Base
  has_and_belongs_to_many :poems
  
    def keyword_description
                "#{self.keyword_id}"
        end

end

app/models/poem.rb
class Poem < ActiveRecord::Base
	has_and_belongs_to_many :keywords

	 def keyword_description
          if self.keywords.empty?
            "Brak slow kluczowych"
          else
            self.keywords.map{|c| c.name }.join(", ")
          end
        end
end

app/models/quote.rb
class Quote < ActiveRecord::Base
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  
    def show
      
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/biography_controller.rb
class BiographyController < ApplicationController

  def show
    
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	  
	  @quotes = Quote.all
	end

end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  before_action :set_keyword, only: [:show, :edit, :update, :destroy]
  before_action :set_poem, only: [:show, :edit, :update, :destroy]
  # GET /keywords
  # GET /keywords.json
  def index
    @keywords = Keyword.all
  end

  # GET /keywords/1
  # GET /keywords/1.json
  def show
  end

  # GET /keywords/new
  def new
    @keyword = Keyword.new
  end

  # GET /keywords/1/edit
  def edit
  end

  # POST /keywords
  # POST /keywords.json
  def create
    @keyword = Keyword.new(keyword_params)

    respond_to do |format|
      if @keyword.save
        format.html { redirect_to @keyword, notice: 'Keyword was successfully created.' }
        format.json { render action: 'show', status: :created, location: @keyword }
      else
        format.html { render action: 'new' }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keywords/1
  # PATCH/PUT /keywords/1.json
  def update
    respond_to do |format|
      if @keyword.update(keyword_params)
        format.html { redirect_to @keyword, notice: 'Keyword was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keywords/1
  # DELETE /keywords/1.json
  def destroy
    @keyword.destroy
    respond_to do |format|
      format.html { redirect_to keywords_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_keyword
      @keyword = Keyword.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def keyword_params
      params.require(:keyword).permit(:name, :description, {:poem_ids =>[]})
    end
    
    def set_poem
        @poem = Poem.find(:all).map do |poem|
                [poem.title, poem.id]
            end
    end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

    def show
      
    end
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  before_action :set_poem, only: [:show, :edit, :update, :destroy, :keyword]
  before_action :set_keywords, only: [:new, :edit, :update, :create]

  # GET /poems
  # GET /poems.json
  def index
    @poems = Poem.all
  end

  # GET /poems/1
  # GET /poems/1.json
  def show
  end

  # GET /poems/new
  def new
    @poem = Poem.new
  end

  # GET /poems/1/edit
  def edit
  end

  # POST /poems
  # POST /poems.json
  def create
    @poem = Poem.new(poem_params)

    respond_to do |format|
      if @poem.save
        format.html { redirect_to @poem, notice: 'Poem was successfully created.' }
        format.json { render action: 'show', status: :created, location: @poem }
      else
        format.html { render action: 'new' }
        format.json { render json: @poem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /poems/1
  # PATCH/PUT /poems/1.json
  def update
    respond_to do |format|
      if @poem.update(poem_params)
        format.html { redirect_to @poem, notice: 'Poem was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @poem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /poems/1
  # DELETE /poems/1.json
  def destroy
    @poem.destroy
    respond_to do |format|
      format.html { redirect_to poems_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poem
      @poem = Poem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poem_params
      params.require(:poem).permit(:title, :incipit, :meter, :volume, :year, :poem, {:keyword_ids => []})
    end
    
    def set_keywords
        @keywords = Keyword.find(:all).map do |keyword|
                [ keyword.name, keyword.id ]
        end
    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render action: 'show', status: :created, location: @quote }
      else
        format.html { render action: 'new' }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:quote, :title)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/biography_helper.rb
module BiographyHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/about/index.html.erb
<h1>O projekcie</h1>

app/views/biography/index.html.erb
<h1>Biografia</h1>

app/views/home/index.html.erb
<h1>Strona główna</h1>
<% @quotes.each do |quote| %>
      <ul> <li><%= quote.quote %> <br /><%= quote.title %></li>
      </ul>    
<% end %>

app/views/keywords/_form.html.erb
<%= form_for(@keyword) do |f| %>
  <% if @keyword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@keyword.errors.count, "error") %> prohibited this keyword from being saved:</h2>

      <ul>
      <% @keyword.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/keywords/edit.html.erb
<h1>Editing keyword</h1>

<%= render 'form' %>

<%= link_to 'Show', @keyword %> |
<%= link_to 'Back', keywords_path %>

app/views/keywords/index.html.erb
<h1>Listing keywords</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Poems</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @keywords.each do |keyword| %>
      <tr>
        <td><%= link_to keyword.name, keyword %></td>
		<td><% keyword.poems.each do |poem| %>
		<h3 class="keyword_poems">
		<%= link_to poem.title, poem %>
		</h3>
		<% end %>
		</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/keywords/new.html.erb
<h1>New keyword</h1>

<%= render 'form' %>

<%= link_to 'Back', keywords_path %>

app/views/keywords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @keyword.name %>
</p>

<p>
  <strong>Desc:</strong>
	<%= simple_format(@keyword.description.gsub(/\n/, '<br/>')) %>
</p>


<%= link_to 'Back', keywords_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="foot">
  <nav>
  	<ul>
    <li><%= link_to 'Strona główna', root_path %></li>        
	<li><%= link_to 'O projekcie', about_path %></li>
        <li><%= link_to 'Czesław Miłosz - biografia', biography_path %></li>
        <li><%= link_to 'Wiersze', poems_path %></li>
	<li><%= link_to 'Linki', links_path %></li>
</ul>
  </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container head">
<nav>
<ul>
	<li><%= link_to 'Strona główna', root_path %></li>        
	<li><%= link_to 'O projekcie', about_path %></li>
        <li><%= link_to 'Czesław Miłosz - biografia', biography_path %></li>
        <li><%= link_to 'Wiersze', poems_path %></li>
	<li><%= link_to 'Linki', links_path %></li>
</ul>
</nav>

    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project Milosz</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>
<%= render 'layouts/shim' %>
<div id="logo"><%= image_tag image_path('text.svg') %></div>

<section id="content" class="center"><%= yield %></section>


<%= render 'layouts/footer' %>
</body>
</html>

app/views/links/index.html.erb
<h1>Linki</h1>

app/views/poems/_form.html.erb
<%= form_for(@poem) do |f| %>
  <% if @poem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@poem.errors.count, "error") %> prohibited this poem from being saved:</h2>

      <ul>
      <% @poem.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :incipit %><br>
    <%= f.text_field :incipit %>
  </div>
  <div class="field">
    <%= f.label :meter %><br>
    <%= f.text_field :meter %>
  </div>
  <div class="field">
    <%= f.label :volume %><br>
    <%= f.text_field :volume %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :poem %><br>
    <%= f.text_area :poem %>
  </div>
  
   <div class="field">
    <%= f.label 'Słowa kluczowe' %><br>
    <%= f.select :keyword_ids, @keywords, {}, :multiple => true %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/poems/edit.html.erb
<h1>Editing poem</h1>

<%= render 'form' %>

<%= link_to 'Show', @poem %> |
<%= link_to 'Back', poems_path %>

app/views/poems/index.html.erb
<h1>Wiersze</h1>

<table>
  <thead>
    <tr>
      <th>Tytuł</th>
      <th>Incipit</th>
      <th>Metrum</th>
      <th>Tom</th>
      <th>Rok</th>
      <th>Słowa kluczowe</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @poems.each do |poem| %>
      <tr>
        <td><%= poem.title %></td>
        <td><%= poem.incipit %></td>
        <td><%= poem.meter %></td>
        <td><%= poem.volume %></td>
        <td><%= poem.year %></td>
        <td><% poem.keywords.each do |keyword| %>
                <h3 class="poem_keywords">
                <%= link_to keyword.name, keyword %>
                </h3>
                <% end %></td>

        <td><%= link_to 'Pokaż', poem %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Dodaj wiersz', new_poem_path %>
<%= link_to 'Słowa kluczowe', keywords_path %>

app/views/poems/new.html.erb
<h1>New poem</h1>

<%= render 'form' %>

<%= link_to 'Back', poems_path %>

app/views/poems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @poem.title %>
</p>

<p>
  <strong>Incipit:</strong>
  <%= @poem.incipit %>
</p>

<p>
  <strong>Poem:</strong>
  <%= simple_format(@poem.poem.gsub(/\n/, '<br/>')) %>
</p>


<p>
  <strong>Meter:</strong>
  <%= @poem.meter %>
</p>

<p>
  <strong>Volume:</strong>
  <%= @poem.volume %>
</p>

<p>
  <strong>Year:</strong>
  <%= @poem.year %>
</p>



<%= link_to 'Edytuj', edit_poem_path(@poem) %>
<%= link_to 'Usuń', @poem, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Wróć do wierszy', poems_path %>

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quote %><br>
    <%= f.text_field :quote %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<h1>Listing quotes</h1>

<table>
  <thead>
    <tr>
      <th>Quote</th>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.quote %></td>
        <td><%= quote.title %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quote:</strong>
  <%= @quote.quote %>
</p>

<p>
  <strong>Title:</strong>
  <%= @quote.title %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>